name: Release Build

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Install dependencies on macOS
      if: runner.os == 'macOS'
      run: brew install cmake

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      shell: bash

    - name: Build
      run: cmake --build build --config Release
      shell: bash

    - name: Package binary
      run: |
        mkdir dist
        cp build/Release/xdk-extractor.exe dist/
        cp build/xdk_extractor dist/
        cd dist
        zip ../xdk_extractor-${{ runner.os }}.zip * || tar -czf ../xdk_extractor-${{ runner.os }}.tar.gz *
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: xdk_extractor-${{ runner.os }}
        path: |
          xdk_extractor-${{ runner.os }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}